version: '3.8'

services:
  mock-server:
    build: ./app
    command: python3 /app/mock_server.py
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    networks:
      - sim-net
  modbus-service:
    build: ./app
    command: python3 /app/main.py
    devices:
      - "/dev/cu.usbserial-10:/dev/ttyS0"
    volumes:
      - ./app:/app
    networks:
      - sim-net

networks:
  sim-net:
    driver: bridge